// witnesses.ts
// TypeScript witness implementations for living-dividend-v1.compact
//
// Witnesses are prover-side code — they run OFF-CHAIN when a user (or
// keeper) is generating a ZK proof to submit a transaction. The circuit
// then verifies the witness result in-circuit via cheaper assertions.
//
// Compact declares witnesses; TypeScript provides the runtime.
//
// Usage: this module is imported by the contract's compiled TS wrapper
// (generated by compactc). The `Contract` class from midnight-js-contracts
// takes a witness map keyed by witness name.
//
// STATUS: reference implementation alongside living-dividend-v1.compact.

import {
  type UserAddress,
  type WitnessContext,
} from '@midnight-ntwrk/compact-runtime';
import * as ed25519 from '@noble/ed25519';

// ─── types matching contract structs ──────────────

interface DivResult {
  quotient:  bigint;   // Uint<128>
  remainder: bigint;   // Uint<128>
}

// ─── witness_divmod ──────────────────────────────
// Prover computes q, r such that num = q*d + r  (0 <= r < d).
// Contract verifies the equation and r < d in-circuit.
//
// Because the numerator lives in Field space (up to ~254 bits) and both
// q, r are Uint<128>, we do BigInt arithmetic and split.
//
export function witness_divmod(
  _ctx: WitnessContext,
  numerator: bigint,
  divisor: bigint,
): [WitnessContext, DivResult] {
  if (divisor === 0n) {
    // Contract asserts totalLivingMembers > 0 before calling divmod for
    // bumpOnMint, and SCALE is a non-zero constant for claim. This branch
    // should not be reachable in a well-formed tx. Returning zeros lets
    // the in-circuit assertion produce a clean revert.
    return [_ctx, { quotient: 0n, remainder: 0n }];
  }
  const quotient = numerator / divisor;
  const remainder = numerator % divisor;
  return [_ctx, { quotient, remainder }];
}

// ─── witness_multisigSignatureValid ──────────────
// Verifies that the multisig authority (per ADR-002 pattern) has signed
// the given payload. Reuses the same verification pattern EBT v5.2 uses
// for its multisig-owner circuits.
//
// The witness reads the current signature bundle from prover-side context
// (typically set by the admin app before proof generation) and verifies
// each of N-of-M ring signatures against `authorityHash`.
//
// TODO: mirror the exact v5.2 helper — this is the placeholder shape.
//
export function witness_multisigSignatureValid(
  ctx: WitnessContext,
  payload: Uint8Array,       // Bytes<32>
  authorityHash: Uint8Array, // Bytes<32>
): [WitnessContext, boolean] {
  // Retrieve the pre-loaded signature bundle from proverState.
  // In v5.2 this is a `MultisigBundle { signers, sigs, threshold }`.
  const bundle = (ctx.privateState as any)?.multisigBundle;
  if (!bundle) {
    return [ctx, false];
  }

  // Reuse the v5.2/v7 multisig-bundle verifier (Ed25519 verify per signer,
  // threshold check, authorityHash membership check).
  const isValid = verifyMultisigBundle(bundle, payload, authorityHash);
  return [ctx, isValid];
}

// ─── witness_memberSignatureValid ────────────────
// Verifies an Ed25519 signature by the member's UserAddress key over payload.
// UserAddress here is a struct { bytes: Bytes<32> }; the bytes ARE the
// Ed25519 public key.
//
// The signature bytes come from proverState (set by the mobile app when
// building a claim/touch tx).
//
export function witness_memberSignatureValid(
  ctx: WitnessContext,
  member: { bytes: Uint8Array },   // UserAddress
  payload: Uint8Array,             // Bytes<32> — the hash being signed
): [WitnessContext, boolean] {
  const sig = (ctx.privateState as any)?.memberSignature;
  if (!sig || sig.length !== 64) {
    return [ctx, false];
  }
  try {
    const isValid = ed25519.verify(sig, payload, member.bytes);
    return [ctx, isValid];
  } catch {
    return [ctx, false];
  }
}

// ─── witness_blockTimeGte ────────────────────────
// L-3 hardening: verifies that the caller-supplied `currentTime` is not
// in the future relative to the current block time.
//
// The prover reads the latest known block time from ctx (fetched from
// indexer at proof-gen time) and returns true iff blockTime >= t.
//
// This mirrors the v5.2 / v7 pattern for timestamp binding.
//
export function witness_blockTimeGte(
  ctx: WitnessContext,
  t: bigint,   // Uint<64>
): [WitnessContext, boolean] {
  const blockTime: bigint = (ctx.privateState as any)?.blockTime ?? 0n;
  return [ctx, blockTime >= t];
}

// ─── witness map export ──────────────────────────
export const witnesses = {
  witness_divmod,
  witness_multisigSignatureValid,
  witness_memberSignatureValid,
  witness_blockTimeGte,
};

// ─── helper stubs (to be wired to the operator's multisig helper) ──

/**
 * Reference declaration. Wire to the multisig-bundle verifier used by the
 * rest of the PollPower contract family (same shape v5.2/v7 uses).
 */
declare function verifyMultisigBundle(
  bundle: {
    signers: Uint8Array[];
    sigs:    Uint8Array[];
    threshold: number;
  },
  payload: Uint8Array,
  authorityHash: Uint8Array,
): boolean;
